Callback:
  output_dir: /data1/xiaonahu/output/output_32_64_128_loose/
Dataset:
  batch_size: 32
  data_path: /home/xiaonanhu/learning/dataset_no_img/
  drop_last: true
  local:
    blocksize:
    - 32
    - 64
    - 128
    local: true
    output_stride:
    - 16
    - 16
    - 16
  num_workers: 10
  pin_memory: true
  shuffle: true
  validation:
  - val
  - test
Loss:
  loss: L1
  use_mask: false
Model:
  blocksize_list:
  - 32
  - 64
  - 128
  decodemode: GlobalAttention
  gamma: true
  mode: GlobalAttention
  mullayer: false
  name: local_count_mutihead_loose
  norm_pix_loss: true
  output_stride_list:
  - 16
  - 16
  - 16
  similarityfunc: PatchConv
  similaritymode: OutputAdd
  xenhance: false
  depth: 11
Optimizer:
  accum_iter: 1
  blr: 0.0002
  epochs: 400
  lr: 0.0001
  min_lr: 0
  start_epoch: 351
  warmup_epochs: 10
  weight_decay: 0.05
Resume:
  checkpoint: True
  resume_path: "/data1/xiaonahu/output/output_32_64_128_loose/checkpoint-270.pth"
Training:
  device: cuda
  seed: 728
  use_enhance_density: false
logger:
  log: true
  log_path: /data1/xiaonahu/output/output_32_64_128_loose/
